### ISSUE TITLE
Кодовая синхронизация репозиториев skypeopensource2 с skypeopensource2_dev

### ISSUE THREAD

**Issue by AntonBoch1244** [skypeopensource/skypeopensource2_dev#2]
Я предлагаю закрыть репозиторий skypeopensource2_dev и создать ветку dev в репозитории skypeopensource2 и сделать её главной так как англоязычные пользователи заливают свой код в этот репозиторий и им попросту не нужен другой репозиторий.
А синхронизацию веток проводить методом который указан в git wiki.

В случае принятия данного решения:
 1. Ваш код будет сохранен.
 1. Стабильный код не будет затронут до того момента когда ветка dev мержнется.
 1. Уберётся рутина с перемещением файлов из 1 репозитория в другой на вашей машине.
 1. У контрибюторов будет возможность писать код где надо, а не где попало.

В случае отказа от данного решения:
 1. Ваш код будет сохранен.
 1. Стабильный код не будет затронут до того момента когда файлы на вашей машине отправятся в master.
 1. Останется рутина с перемещением файлов из 1 репозитория в другой на вашей машине.
 1. Контрибюторы будут не понимать куда вообще всё это кидается(Вне зависимости от существования CONTRIBUTING.md).

**Comment by AntonBoch1244** [comment]
REF: skypeopensource/skypeopensource2#11

**Comment by AntonBoch1244** [comment]
@skypeopensource жду вашего решения.

**Comment by skypeopensource** [comment]
@AntonBoch1244 

Репозиторий skypeopensource2 это копия zip-архива. Она не будет и на планируется развиваться.

**Comment by skypeopensource** [comment]
skypeopensource2_dev -- будет активным репозиторием для windows версии.

 skypeopensource2_linux -- будет активным репозиторием для linux версии

**Comment by AntonBoch1244** [comment]
@skypeopensource Код один, зачем его разделять. Нету смысла в его разделении!

**Comment by Randl** [comment]
@skypeopensource Для того чтобы сохранить конкретную версию в git, следует использовать а) ветки б) теги. Все состояния кода хранятся в гит, и любая версия доступна всегда, независимо от будущих изменений. Именно для этого и нужен version control - чтобы не держать конкретную версию в  отдельной папке или архиве, а иметь к ней доступ через дерево коммитов (и теги)
Разные репозитории же используются для разных проектов.
Кроме того, ИМХО делать отдельную Win и Lin версии не стоит, вместо этого надо менять текущий код так, чтобы он был кроссплатформенным и компилировался как минимум в gcc и VS одновременно.

Наличие нескольких проектов серьезно запутывает потенциальных контрибьюторов и пользователей, особенно с учетом того, что "основной" репозиторий вы хотите держать замороженным.

**Comment by skypeopensource** [comment]
@Randl 

Тебе следует, ты и используй. Вопрос закрыт.

**Comment by Randl** [comment]
Нет, это ты не используй git если не умеешь и не понимаешь.

**Comment by AntonBoch1244** [comment]
@skypeopensource, я имею полное право назвать вас идиотом, так как вы не знаете как работает git и его компоненты _ВАМ_ даже объяснили для чего он нужен.
Я наверное буду тоже идиотом, но **ВЫ** **ПРОСТО** **ИГНОРИРУЕТЕ** **ВСЕХ** СВОИХ **КОНТРИБЮТОРОВ** **КОТОРЫЕ** **ПЫТАЮТСЯ** ВАМ **ПОМОЧЬ** **СДЕЛАТЬ** ВСЁ **ТАК** **ЧТОБЫ** ОНО **РАБОТАЛО**!
Прошу прощения за капс, но я не вытерпел этот идиотизм с вашей стороны @skypeopensource.

**Comment by AntonBoch1244** [comment]
Если ты просто в git пишешь содержимое архива и для каждого архива будет свой репозиторий тогда может лучше закрыть проект _dev и _linux, вместо создания 1000000 репозиториев с разной версией и разными исходниками, но исполняющие одно и тоже?
Для чего вообще существует система контроля версий git, subversion, bazar, mercurial? Если она не используется.

**Comment by skypeopensource** [comment]
@AntonBoch1244 будет лучше, если Вы пойдете нахуй.

**Comment by skypeopensource** [comment]
@AntonBoch1244 будет лучше, если Вы пойдете нахуй.
